import { StyleSheet } from "@react-pdf/renderer";

export default StyleSheet.create({
  gstheader: {
    backgroundColor: "#5ACE00",
    display: "flex",
    flexDirection: "row",
    height: "100px",
    paddingLeft: "13px",
    paddingRight: "13px",
    justifyContent: "space-between",
    alignItems: "center",
  },
  contentHeadRight: {
    width: "180px",
    color: "white",
    height: "40px",
    justifyContent: "space-between",
    fontSize: "16px",
    textAlign: "right",
    display: "flex",
    fontFamily: "Helvetica-Bold",
    flexDirection: "column",
  },
  bonusContent: {
    marginTop: "40px",
    marginLeft: "100px",
  },
  bonusTabelHead: {
    backgroundColor: "black",
    color: "white",
    height: "35px",
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    fontSize: "10px",
    width: "85%",
    borderTopLeftRadius: "5px",
    borderTopRightRadius: "5px",
    fontFamily: "Helvetica-Bold",
  },
  bonusHeadNo: {
    width: "50px",
    textAlign: "center",
  },
  bonusHeadCategory: {
    width: "250px",
    textAlign: "center",
  },
  bonusHeadValue: {
    width: "100px",
    textAlign: "center",
  },
  bonusTabelBody: {
    borderLeft: "2px",
    borderRight: "2px",
    borderBottom: "2px",
    width: "85%",
    display: "flex",
    flexDirection: "row",
    height: "120px",
    fontSize: "12px",
  },
  bonusBodyNo: {
    width: "50px",
    textAlign: "center",
    paddingBottom: "5px",
    paddingTop: "5px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    borderRight: "1px",
    borderStyle: "dashed",
  },
  bonusBodyCategory: {
    width: "250px",
    paddingLeft: "20px",
    paddingBottom: "5px",
    paddingTop: "5px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    borderRight: "1px",
    borderStyle: "dashed",
  },
  bonusBodyValue: {
    width: "100px",
    textAlign: "center",
    paddingBottom: "5px",
    paddingTop: "5px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
  },
  salesContent1: {
    width:'100%',
    paddingLeft:'13px',
    paddingRight:'13px',
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:'30px'
  },
  salesBillFromContact:{
    border:'1px',
    width:'35%',
    borderRadius:'3px',
    paddingLeft:'8px',
    paddingRight:'8px',
    borderColor:'#dbdbdb',
    height:'47px',
    display:'flex',
    flexDirection:'column',
    justifyContent:'space-around'
  },
  salesBillGstInContact:{
    border:'1px',
    borderRadius:'3px',
    width:'25%',
    paddingLeft:'8px',
    paddingRight:'8px',
    borderColor:'#dbdbdb',
    height:'47px',
    display:'flex',
    flexDirection:'column',
    justifyContent:'space-around'
  },
  salesBillContactNumber:{
    border:'1px',
    borderRadius:'3px',
    width:'15%',
    paddingLeft:'8px',
    paddingRight:'8px',
    borderColor:'#dbdbdb',
    height:'47px',
    display:'flex',
    flexDirection:'column',
    justifyContent:'space-around'
  },
  salesBillContactDate:{
    border:'1px',
    width:'15%',
    borderRadius:'3px',
    paddingLeft:'8px',
    paddingRight:'8px',
    borderColor:'#dbdbdb',
    height:'47px',
    display:'flex',
    flexDirection:'column',
    justifyContent:'space-around'
  },
  salesBillContactHead: {
    fontSize:'9px',
    color:'#707070'
  },
  salesBillContactBody: {
    fontSize:'10px',
    color:'#232E38',
    opacity:1
  },
  contentTitle: {
    marginBottom:'10px',
    fontFamily: "Helvetica-Bold"
  },
  salesContentPurchase: {
    minHeight:'110px',
    marginTop: "18px",
    paddingLeft: "13px",
    paddingRight: "13px",
    width: "100%",
  },
  salesContent: {
    minHeight:'110px',
    marginTop: "18px",
    paddingLeft: "13px",
    paddingRight: "13px",
    width: "100%",
    borderBottom:'2px',
    borderColor:'#dbdbdb',
  },
  salesTabelHead: {
    backgroundColor: "black",
    color: "white",
    height: "28px",
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    fontSize: "7px",
    width: "100%",
    borderRadius: "5px",
    fontFamily: "Helvetica-Bold",
  },
  salesHeadNo: {
    width: "40px",
    textAlign: "center",
  },
  salesHeadSalesBillNo:{
    width: "120px",
    textAlign: "center",
  },
  salesHeadInDate: {
    width: "80px",
    textAlign: "center",
  },
  salesHeadCmpName: {
    width: "220px",
    textAlign: "center",
  },
  salesHeadGstNum: {
    width: "120px",
    textAlign: "center",
  },
  salesBodyBillCost: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "90px",
    textAlign: "center",
  },
  salesBodyGstAmt: {
    display: "flex",
    flexDirection: "row",
    alignContent:'center',
    width: "90px",
    textAlign: "center",
  },
  salesBodyAmount: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "90px",
    textAlign: "center",
    paddingRight: "10px",
  },
  salesHeadPaidDate: {
    width: "80px",
    textAlign: "center",
  },
  salesHeadPaidMode: {
    width: "130px",
    textAlign: "center",
  },

  salesTabelBody: {
    height: "32px",
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    fontSize: "7px",
    width: "100%",
    fontFamily: "Helvetica",
  },
  salesHeadNo: {
    width: "40px",
    textAlign: "center",
  },
  salesBodySalesBillNum:{
    width: "120px",
    textAlign: "center",
  },
  salesHeadInDate: {
    width: "80px",
    textAlign:'center'
  },
  salesBodyCmpName: {
    width: "220px",
    textAlign: "center",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  salesBodyGstNum: {
    width: "120px",
    textAlign: "center",
  },
  salesHeadBillCost: {
    width: "90px",
    textAlign: "center",
  },
  salesHeadGstAmt: {
    width: "90px",
    textAlign: "center",
  },
  salesHeadAmount: {
    width: "90px",
    textAlign: "center",
    paddingRight: "10px",
  },
  salesHeadPaidDate: {
    width: "80px",
    textAlign: "center",
  },
  salesHeadPaidMode: {
    width: "130px",
    textAlign: "center",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  footerContent: {
    display:'flex',
    flexDirection:'column',
    alignItems:'flex-end',
    width:'100%',
    justifyContent:'flex-end',
    paddingLeft:'13px',
    paddingRight:'13px',
    marginBottom:'10px'
  },
  footerText: {
    width:'200px',
    marginBottom:'7px',
    textAlign:'right',
    display:'flex',
    flexDirection:'row',
  },
  footerBillCost:{
    width:'160px',
    textAlign:'right',
    color:'#707070',
    fontSize:'10px'
  },
  footerBillCostRight: {
    width:'90px',
    fontSize:'10px',
    fontFamily: 'Helvetica',
  },
  footerCalc: {
    paddingLeft:'13px',
    // paddingRight:'13px',
    display:'flex',
    flexDirection:'row',
    justifyContent:'flex-end'
  },
  footerCalcLeft:{
    marginTop:'9px',
    height:'70px',
    justifyContent:'space-between',
    width:'35%',
    display:'flex',
    flexDirection:'column',
    alignItems:'flex-end'
  },
  footerCalcLeftContent:{
    width:'100%',
    marginBottom:'7px',
    display:'flex',
    flexDirection:'column',
    justifyContent:'space-around'
  },
  footerCalcRight:{
    marginTop:'25px',
    width:'100%',
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-around',
    alignItems:'center'
  },
  footerRightCalcTop: {
    width:'120px',
    fontSize:'7px',
    color:'#707070',
    paddingLeft:'8px'
  },
  footerRightCalcBottom: {
    marginTop:'10px',
    borderRadius:'3px',
    fontSize:'15px',
    color:'#232E38',
    opacity:1,
    backgroundColor:'#F6F6F6',
    width:'130px',
    height:'40px',
    fontFamily: "Helvetica",
    display:'flex',
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
  },

  footerImage: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "33%",
  },
  pdfFooterContent: {
    fontSize: "8px",
  },
  pdfFooter: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingLeft: "12px",
    paddingRight: "12px",
    paddingTop: "6px",
    paddingBottom: "6px",
    backgroundColor: "#F3F3F3",
  },
});
