describe('empty spec', () => {
    it('passes', () => {
      cy.visit('http://localhost:3000/chitEmi')
      cy.get('#amount').click()
      cy.wait(2000)
      cy.get('#amountValue').type('100000')
      cy.wait(2000)
      cy.get('#amountCommission').select('5')
      cy.wait(2000)
      cy.get('#amountTotalMonth').type('20')
      cy.wait(2000)
      cy.get('#amountPresentMonth').type('1')
      cy.wait(2000)
      cy.get('#amountCalculate').click()
      cy.wait(2000)
      cy.get('#download').click()
      cy.wait(2000)
      cy.get('#pdf').click()
      cy.wait(2000)
      cy.get('#download').click()
      cy.wait(2000)
      cy.get('#excel').click()
      cy.wait(2000)
    //   cy.get('#download').click()
    //   cy.wait(2000)
      cy.get('#amountClear').click()
      cy.wait(2000)
      cy.get('#bonus').click()
      cy.wait(2000)
      cy.get('#bonusValue').type('100000')
      cy.wait(2000)
      cy.get('#bonusTotalMonth').type('20')
      cy.wait(2000)
      cy.get('#bonusCommission').select('5')
      cy.wait(2000)
      cy.get('#bonusPresentMonth').type('8')
      cy.wait(2000)
      cy.get('#bonusCalculate').click()
      cy.wait(2000)
      cy.get('#download').click()
      cy.wait(2000)
      cy.get('#pdf').click()
      cy.wait(2000)
      cy.get('#download').click()
      cy.wait(2000)
      cy.get('#excel').click()
      cy.wait(2000)
    //   cy.get('#download').click()
    //   cy.wait(2000)
      cy.get('#bonusClear').click()
      cy.wait(2000)
      cy.get('#emi').click()
      cy.wait(2000)
      cy.get('#emiValue').type('500000')
      cy.wait(2000)
      cy.get('#emiRate').type('12')
      cy.wait(2000)
      cy.get('#emiLoan').type('20')
      cy.wait(2000)
      cy.get('#emiCalculate').click()
      cy.wait(2000)
      cy.get('#download').click()
      cy.wait(2000)
      cy.get('#pdf').click()
      cy.wait(2000)
      cy.get('#download').click()
      cy.wait(2000)
      cy.get('#excel').click()
      cy.wait(2000)
    //   cy.get('#download').click()
    //   cy.wait(2000)
      cy.get('#emiClear').click()

    })
  })