import { StyleSheet } from "@react-pdf/renderer";

export default StyleSheet.create({
    page: {
      flexDirection: 'column',
      backgroundColor: '#FFFFFF',
    },
    pageContiner:{
      minHeight:"96vh",
    },
    headercontent:{
      height:150,
      fontSize:10,
      width:560,
      paddingLeft:28,
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:"center",
      // backgroundColor:"#EED6D3"
    },
    companyDetails:{
      height:120,
      display:"flex",
      // justifyContent:"space-around",
      alignContent:"space-around",
      fontSize:10,
      // backgroundColor: '#FBE7C6',
    },
    companyName:{
      marginBottom:'3px'
    },
    companyAddress:{
      marginBottom:'3px'
    },
    details:{
      height:100,
      justifyContent:"flex-end",
      alignItems:"flex-start"
    },
    text:{
      color:"white",
      width:172,
      fontSize:20,
      color:"white"
    },
    date:{
      fontSize:20,
      fontWeight:"bold"
    },
    datecontiner:{
      height:60,
      justifyContent:"flex-end",
      alignItems:"flex-end"
    },
    monthtext:{
      paddingBottom:10
    },
    // first contents
    detailscontiner:{
      height:"auto",
      flexDirection:"column",
      alignItems:"center",
      justifyContent:"space-between",
      paddingTop:20,
      
    },
    detailsContent:{
      // backgroundColor:"black",
      height:130,
      width:550,
      justifyContent:"space-between",
      borderBottom:"#707070",
      borderBottomStyle:"dashed",
      borderBottomWidth:1,
    },
    contents:{
      flexDirection:'row',
      width:550,
      justifyContent:"space-between"
    },
    employeeDetails:{
      flexDirection:"column",
      justifyContent:"space-around",
      alignItems:"flex-start",
      height:120
    },
    textContiner:{
      flexDirection:"row",
      justifyContent:"space-between",
      width:200
    },
    employeeHeading:{
      fontSize:10,
      paddingLeft:30
    },
    employeeText:{
      fontSize:10,
      paddingLeft:20,
      justifyContent:"flex-end",
      alignItems:"flex-end",
      width:'200px'
    },
    employeOutput:{
      alignItems:"flex-start",
      justifyContent:"flex-start",
      width:100
    },
    h1:{
      paddingLeft:2,
      width:100
    },
    // paymentdetails
    paymentText:{
      fontSize:10,
      
    },
    paymentAmount:{
      fontSize:25,
      paddingBottom:5
    },
    paymentContiner:{
      
    },
    paymentAmountandtext:{
      paddingTop:10,
      paddingBottom:10,
      borderBottom:"#707070",
      borderBottomStyle:"dashed",
      borderBottomWidth:1,
      justifyContent:"center",
      alignItems:"flex-start",
      
    },
    amountdetails:{
      paddingLeft:10,
      width:160
    },
    paydatelop:{
      flexDirection:"row",
      width:200,
      paddingLeft:10,
      paddingBottom:10
    },
    paydateandlop:{
      flexDirection:"row"
    },
    paymenttext:{
      fontSize:10
    },
    paymenttextlop:{
      fontSize:10,
      paddingLeft:10
    },
    // incomedetailscontiner
    incomedetailscontiner:{
      
      height:"auto",
      alignItems:"center",
      justifyContent:"space-around"
    },
    incomedetails:{
      width:550,
      height:"auto",
      // paddingLeft:30
    },
    headingcontiner:{
      paddingLeft:30,
      height:30,
      alignItems:"flex-start",
      justifyContent:"space-around"
    },
    heading:{
      fontSize:15,
      
    },
    headingsymbol:{
      color:"#FF0303"
    },
    earningsanddeductions:{
      flexDirection:"row",
      justifyContent:"space-between"
    },
    earningscontiner:{
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:"center",
      width:250,
      height:30,
      borderBottom:"#707070",
      borderBottomStyle:"dashed",
      borderBottomWidth:1,
      paddingLeft:30
      
    },
    earningsdetails:{
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:"center",
      fontSize:10,
      width:200
    },
    earningsoutputcontiner:{
      // backgroundColor:"white",
      flexDirection:"column",
      justifyContent:"space-around",
      alignItems:"center",
      fontSize:10,
      width:250,
     
    },
    earningsoutput:{
     flexDirection:"row",
     width:250,
     justifyContent:"space-between",
     paddingTop:10,
     paddingBottom:10,
     
    },
    earningstext:{
      width:80
    },
    titleanddot:{
      justifyContent:"space-between",
      width:150,
      flexDirection:"row",
      paddingLeft:30.5
    },
    earningsvalue:{
      width:37
    },
    deductionstitleanddot:{
      justifyContent:"space-between",
      width:100,
      flexDirection:"row",
    },
    earningsoutputtwo:{
      flexDirection:"row",
      justifyContent:"space-between",
      width:250,
      paddingLeft:30,
      paddingRight:20
    },
    incomeDeductions:{
      flexDirection:"row",
      justifyContent:"space-between",
    },
    // totaldesign
    totalcontiner:{
      height:80,
      alignItems:"center",
      justifyContent:"center"
    }
    ,totalcontent:{
      borderRadius:5,
      backgroundColor:"#E9E9E9",
      height:45,
      width:550,
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:"center"
    },
    totaltext:{
      flexDirection:"row",
      fontSize:10,
      width:250,
      justifyContent:"space-between",
      alignItems:"center",
      paddingLeft:30
    },
    totaltexttwo:{
      flexDirection:"row",
      fontSize:10,
      width:250,
      justifyContent:"space-between",
      alignItems:"center",
      paddingLeft:30,
      paddingRight:20
    },
    totalamount:{
      backgroundColor:"white",
      height:30,
      width:90,
      alignItems:"center",
      justifyContent:"center",
      borderRadius:5,
    },
    overalltotalcontiner:{
      
      alignItems:"center",
      justifyContent:"center",
      height:150
      
    },
    overalltotal:{
      alignItems:"center",
      justifyContent:"space-between",
      flexDirection:"column",
      height:70,
      width:550
    },
    overalltext1:{
      fontSize:25
    },
    overalltext2:{
      fontSize:10
    },
    overalltext3:{
      fontSize:7
    },
    summarycontiner:{
      height:170,
      justifyContent:"flex-end",
      alignItems:"center"
    },
    summary:{
      width:550,
      height:35,
      justifyContent:"space-between",
    },
    summarypara:{
      fontSize:6.5
    },
    summaryheading:{
      fontSize:10
    },
    rupeeSymbol:{
      height:16,
      width:16
    },
    imageout:{
      height:50,
      width:"auto",
      marginBottom:5,
      objectFit:"contain",
      paddingBottom:5
    },
    pdfFooter:{
      display:'flex',
      flexDirection:'row',
      justifyContent:'flex-end',
      alignItems:'center',
      paddingLeft:'12px',
      paddingRight:'12px',
    paddingTop:'6px',
    paddingBottom:'6px',
      backgroundColor:'#F3F3F3'
      },
       pdfFooterContent:{
      fontSize:'6px',
      },
      footerImage: {
      display:'flex',
      flexDirection:'row',
       justifyContent:'space-around',
    alignItems:'center',
      width:'33%'
    },
      
    paySummaryMap:{
      alignItems:"flex-start",
      display:"flex",
      width:550
    },
    PaySummary:{
      display:"flex",
      flexDirection:"row",
      flexWrap:"wrap",
      justifyContent:"space-between",
      height:"auto",
      width:550,
      paddingRight:23
    },
    PaySummarytext:{
      fontSize:10
    },
    FooterTextAll:{
      display:"flex",
      flexDirection:"column",
      alignItems:"flex-start",
      justifyContent:"flex-start"
    },
    FooterText1:{
      fontFamily:15,
      fontWeight:"bold"
    },
    FooterText2:{
      fontSize:8
    },
    pdffootertext:{
      display:"flex",
      flexDirection:"column",
      fontSize:5
    }
  });