import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import Card from "../../components/salarycalculator/Card";
import { useCallback, useState } from "react";
import Footer from "../../components/salarycalculator/footer/Footer";
import BtoolsHeader from "../../container/72BTheader/BToolsHeader";
import FeedBackButton from "../../container/72FeedBackButton/feedBackButton";
import BtoolsFooter from "../../container/72BTfooter/BToolsFooter";
import CurrencyPopUp from "../billHive/currency-popup/CurrencyPopUp";

const PdfProvider = dynamic(
  () => import("../../components/invoicegenerator/pdf-provider/PdfProvider"),
  {
    ssr: false,
  }
);
export default function SalaryCalculator() {
  const [salaryDetails, setSalaryDetails] = useState({});
  const [isCurrency,setIsCUrrency] = useState(false)
  const [currencySymbol,setCurrencySymbol] = useState('₹')
  const [currencyId,setCurrencyId] = useState('INR')
  const onSalaryChange = useCallback(
    (salary) => {
      setSalaryDetails(salary);
    },
    [salaryDetails]
  );
  const currencyClick = ()=>{
    setIsCUrrency(true)
  }

  const CurrencyValue = (currencySymbols) => {
    setCurrencySymbol(currencySymbols);
  };
  const setCurrencyIdValue = (currencyIds) => {
    setCurrencyId(currencyIds)
  };
  const setClosePopUp = (closeCurrency) => {
    setIsCUrrency(closeCurrency)
  };
  return (
    <div className="">
      {isCurrency ? <CurrencyPopUp myCurrencySymbol={CurrencyValue}
            myCurrencyId={setCurrencyIdValue}
            closeCurrencyPopUp={setClosePopUp}/> : null}
      {/* <nav className="fixed bg-white shadow-md  z-50 w-full px-5 py-2 flex justify-start indent-2 ">
        <div className="font-['sf-pro-bold'] w-7 h-7 flex flex-row">
          <Image src={abs} className="" alt="search"></Image>
        </div>
        <div className="indent-2 font-['sf-pro-bold'] text-lg text-black text-opacity-80">ABS</div>
        <div className="border-l-2 border-[#878787] indent-2 mx-1 text-[#878787] font-['sf-pro-regular'] flex flex-row">
          <div className="w-7 h-7"> <Image src={salaryicon} className="" alt="search"></Image></div>
          <div> Salary Calculator</div>
        </div>

      </nav> */}
      <div className="flex justify-between items-center pr-2">
        <BtoolsHeader
          Src="/images/Salary Calculator.png"
          Height="35"
          Width="110"
        />
        <div>
              <input
                className="w-[35%] font-[sf-pro-medium] pl-2 text-[12px] bg-transparent"
                value="Currency:"
              />
              <select
                id="currencyPopUp"
                className={
                  "text-[12px] bg-transparent font-[sf-pro-medium] cursor-pointer outline-none"
                }
                onClick={currencyClick}
              >
                <option>
                  {currencyId}({currencySymbol})
                </option>
              </select>
        </div>
      </div>
      <div
        className="w-full h-[92vh] overflow-scroll no-scrollbar 
      flex flex-col bg-[#F5F5F5]"
      >
        <Head>
          <title>Salary to Hourly-Paycheck Calculator</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Card onSalaryChange={onSalaryChange} currencyData={currencySymbol}/>
      </div>

      <div className="bg-blue-300">
        <FeedBackButton
          Src="/images/GST One Pro.png"
          Path="/"
          appName="InvoiceGenerator"
        />
        <BtoolsFooter />
      </div>
    </div>
  );
}
