
import React from "react";

const GlobalContext = React.createContext({
  smallCalendarMonth: 0,
  setSmallCalendarMonth: () => {},
  monthIndex: 0,
  setMonthIndex: (index) => {},
  daySelected: null,
  setDaySelected: (day) => {},
  showEventModal: false,
  setShowEventModal: () => {},
  dispatchCalEvent: ({ type, payload }) => {},
  dispatchCalAttendance: ({ type, payload }) => {},
  savedEvents: [],
  selectedEvent: null,
  setSelectedEvent: () => {},
  setLabels: () => {},
  labels: [],
  updateLabel: () => {},
  filteredEvents: [],
  selectedCardValue:null,
  setSelectedCardValue:(data)=>{},
  selectedCardId:null,
  setSelectedCardId:(proname)=>{},
  setWeekIndex:()=>{},
  WeekIndex:0,
  OpenViewPopup:null,
  setOpenViewPopup:(data)=>{},
  OpenPopupPage:null,
  setOpenPopupPage:(data)=>{},
  changeDashBoard:null,
  setChangeDashBoard:(data)=>{},
  selectedemployee:null,
  setSelectedemployee:(data)=>{},
  CalendarData:null,
  setCalendarData:(data)=>{},
  sendCountDB:null,
  setDbCount:(data)=>{},
  dashBoardData:null,
  setDashBoardData:(data)=>{},
  sentCalenderData:null,
  setSentCalenderData:(data)=>{},
  setSentUseffectCall:(data)=>{},
  sentUseffectCall:null,
  sendEmployee:null,
  setSendEmployee:(data)=>{},
  getDashPopup:null,
  setGetDashPopup:(data)=>{},

});

export default GlobalContext;